In [36]:
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
select * from facilities
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
  
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [37]:
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
# /* Q10: Produce a list of facilities with a total revenue less than 1000.
# The output of facility name and total revenue, sorted by revenue. Remember
# that there's a different cost for guests and members! */ 
    query1 = """
select * 
from 

(select ss.f, sum(ss.c) as tr
from 

(select Facilities.name as f, 
case when Bookings.memid =0
then Facilities.guestcost * Bookings.slots
else Facilities.membercost * Bookings.slots
end as c
from Bookings
join Facilities on Bookings.facid = Facilities.facid
join Members on Bookings.memid = Members.memid) ss

group by ss.f) ss2

where ss2.tr <1000
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
  
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Pool Table', 270)
('Snooker Table', 240)
('Table Tennis', 180)

In [38]:
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
#/* Q12: Find the facilities with their usage by member, but not guests */
    query1 = """
select * 
from 

(select Facilities.name as n, Members.memid as m
from Bookings
join Facilities on Bookings.facid = Facilities.facid
join Members on Bookings.memid = Members.memid) ss

where ss.m>0
group by ss.n, ss.m;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
  
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 1)
('Badminton Court', 2)
('Badminton Court', 3)
('Badminton Court', 5)
('Badminton Court', 6)
('Badminton Court', 7)
('Badminton Court', 8)
('Badminton Court', 9)
('Badminton Court', 10)
('Badminton Court', 11)
('Badminton Court', 12)
('Badminton Court', 13)
('Badminton Court', 14)
('Badminton Court', 15)
('Badminton Court', 16)
('Badminton Court', 17)
('Badminton Court', 21)
('Badminton Court', 24)
('Badminton Court', 26)
('Badminton Court', 29)
('Badminton Court', 30)
('Badminton Court', 33)
('Badminton Court', 35)
('Badminton Court', 36)
('Massage Room 1', 1)
('Massage Room 1', 2)
('Massage Room 1', 3)
('Massage Room 1', 4)
('Massage Room 1', 5)
('Massage Room 1', 6)
('Massage Room 1', 7)
('Massage Room 1', 8)
('Massage Room 1', 9)
('Massage Room 1', 10)
('Massage Room 1', 11)
('Massage Room 1', 12)
('Massage Room 1', 13)
('Massage Room 1', 14)
('Massage Room 1', 16)
('Massage Room 1', 17)
('Massage Room 1', 20)
('Massage Room 1', 21)
('Massage Room 1', 22)
('Massage Room 1', 24)
('Massage Room 1', 29)
('Massage Room 1', 33)
('Massage Room 1', 35)
('Massage Room 1', 36)
('Massage Room 2', 3)
('Massage Room 2', 4)
('Massage Room 2', 5)
('Massage Room 2', 7)
('Massage Room 2', 10)
('Massage Room 2', 11)
('Massage Room 2', 12)
('Massage Room 2', 14)
('Massage Room 2', 15)
('Massage Room 2', 20)
('Massage Room 2', 22)
('Massage Room 2', 24)
('Pool Table', 1)
('Pool Table', 2)
('Pool Table', 3)
('Pool Table', 4)
('Pool Table', 5)
('Pool Table', 6)
('Pool Table', 7)
('Pool Table', 8)
('Pool Table', 9)
('Pool Table', 10)
('Pool Table', 11)
('Pool Table', 12)
('Pool Table', 13)
('Pool Table', 14)
('Pool Table', 15)
('Pool Table', 16)
('Pool Table', 17)
('Pool Table', 20)
('Pool Table', 21)
('Pool Table', 22)
('Pool Table', 24)
('Pool Table', 26)
('Pool Table', 27)
('Pool Table', 28)
('Pool Table', 29)
('Pool Table', 30)
('Pool Table', 33)
('Snooker Table', 1)
('Snooker Table', 2)
('Snooker Table', 4)
('Snooker Table', 5)
('Snooker Table', 6)
('Snooker Table', 7)
('Snooker Table', 8)
('Snooker Table', 9)
('Snooker Table', 10)
('Snooker Table', 11)
('Snooker Table', 13)
('Snooker Table', 14)
('Snooker Table', 15)
('Snooker Table', 17)
('Snooker Table', 20)
('Snooker Table', 21)
('Snooker Table', 22)
('Snooker Table', 24)
('Snooker Table', 27)
('Snooker Table', 28)
('Snooker Table', 30)
('Snooker Table', 33)
('Squash Court', 1)
('Squash Court', 2)
('Squash Court', 4)
('Squash Court', 5)
('Squash Court', 6)
('Squash Court', 8)
('Squash Court', 9)
('Squash Court', 10)
('Squash Court', 11)
('Squash Court', 12)
('Squash Court', 13)
('Squash Court', 14)
('Squash Court', 15)
('Squash Court', 16)
('Squash Court', 17)
('Squash Court', 21)
('Squash Court', 22)
('Squash Court', 24)
('Squash Court', 26)
('Squash Court', 27)
('Squash Court', 28)
('Squash Court', 30)
('Squash Court', 33)
('Squash Court', 35)
('Table Tennis', 1)
('Table Tennis', 2)
('Table Tennis', 3)
('Table Tennis', 4)
('Table Tennis', 5)
('Table Tennis', 6)
('Table Tennis', 7)
('Table Tennis', 8)
('Table Tennis', 9)
('Table Tennis', 10)
('Table Tennis', 11)
('Table Tennis', 12)
('Table Tennis', 13)
('Table Tennis', 14)
('Table Tennis', 15)
('Table Tennis', 16)
('Table Tennis', 17)
('Table Tennis', 20)
('Table Tennis', 21)
('Table Tennis', 22)
('Table Tennis', 24)
('Table Tennis', 29)
('Table Tennis', 30)
('Table Tennis', 35)
('Table Tennis', 36)
('Tennis Court 1', 2)
('Tennis Court 1', 3)
('Tennis Court 1', 4)
('Tennis Court 1', 5)
('Tennis Court 1', 6)
('Tennis Court 1', 7)
('Tennis Court 1', 8)
('Tennis Court 1', 9)
('Tennis Court 1', 10)
('Tennis Court 1', 11)
('Tennis Court 1', 12)
('Tennis Court 1', 13)
('Tennis Court 1', 14)
('Tennis Court 1', 15)
('Tennis Court 1', 16)
('Tennis Court 1', 17)
('Tennis Court 1', 20)
('Tennis Court 1', 22)
('Tennis Court 1', 24)
('Tennis Court 1', 26)
('Tennis Court 1', 28)
('Tennis Court 1', 35)
('Tennis Court 1', 36)
('Tennis Court 2', 1)
('Tennis Court 2', 2)
('Tennis Court 2', 3)
('Tennis Court 2', 4)
('Tennis Court 2', 5)
('Tennis Court 2', 6)
('Tennis Court 2', 7)
('Tennis Court 2', 8)
('Tennis Court 2', 9)
('Tennis Court 2', 10)
('Tennis Court 2', 11)
('Tennis Court 2', 12)
('Tennis Court 2', 13)
('Tennis Court 2', 14)
('Tennis Court 2', 15)
('Tennis Court 2', 16)
('Tennis Court 2', 24)
('Tennis Court 2', 27)
('Tennis Court 2', 28)
('Tennis Court 2', 30)
('Tennis Court 2', 35)